name: CSDS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y valgrind

    - name: Build
      run: make

    - name: Run tests
      run: make test

    - name: Run Valgrind
      run: make valgrind
